name: 'Setup Groovy SDK'
description: 'Set up the wanted version of the Groovy SDK and 
              add CLI commands to the PATH. Relies on actions/setup-java and SDKMAN.'
author: 'Sébastien Perpignane'

branding:
  icon: 'zap'
  color: 'red'

inputs:
  groovy-version:
    description: 'The Groovy SDK version to setup. If no version is specified, 
    the latest stable version will be selected automatically.'

  java-version:
    description: "Groovy needs a JRE. If you don't specify a java version, Groovy will run with the default JRE
    provided by the OS. If no JRE is available on the OS, Groovy won't work."
    required: false

  java-distribution:
    description: 'Java distribution. Default is temurin'
    required: false
    default: "temurin"

runs:

    using: composite

    steps:
      - name: Install java specific version
        if: ${{ inputs.java-version != '' }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: "Install SDKMAN"
        shell: bash
        run: |
          export SDKMAN_DIR="$HOME/.sdkman" && curl -s "https://get.sdkman.io?rcupdate=false" | bash
          echo "sdkman_dir=$SDKMAN_DIR" >> "$GITHUB_ENV"

      - name: Install Groovy SDK
        id: install_groovy
        shell: bash
        run: |
          if [[ "${{ inputs.groovy-version }}" != "" ]] && [[ ! "${{ inputs.groovy-version }}" =~ [0-9]+\.[0-9]+\.[0-9]+  ]]
          then
            echo "Invalid version"
            exit 1
          fi
          source ${{ env.sdkman_dir }}/bin/sdkman-init.sh
          sdk install groovy "${{ inputs.groovy-version }}"
          for candidate_dir in $(find "${{ env.sdkman_dir }}/candidates" -mindepth 1 -maxdepth 1 -type d); do
            echo "Setting $candidate_dir in PATH"
            echo "$candidate_dir/current/bin" >> $GITHUB_PATH
          done

      - name: Show Groovy information
        shell: bash
        run: |
          groovy -version
          
      
